version: '3.8'
services:
  server:
    image: node:18-alpine
    command: sh -c "npm install ws crypto && node server.js"
    working_dir: /app
    volumes:
      - ./server.js:/app/server.js
    ports:
      - "8080:8080"

  client:
    image: nginx:1.21-alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./assets:/usr/share/nginx/html/assets
    ports:
      - "80:80"
    depends_on:
      - server